### ISSUE TITLE
Publish failing when running multiserver docker compose

### ISSUE THREAD

**Issue by edalex-tom** [opencast/opencast-docker#122]
Encountering a failure to publish event when running Opencast with the provided multiserver docker compose (`docker-compose.multiserver.mariadb.yml`).

**Workflow:** Fast Testing Workflow
**Distrubute to Opencast Media Module**

Workflow fails trying to run the `publish-configure` operation.

```
opencast-presentation_1  | 2019-11-18T01:37:16,950 | WARN  | (DownloadDistributionServiceImpl:359) - Error distributing http://localhost:8080/files/mediapackage/09902b98-ab6d-4893-aacb-28db12405bb6/5adfe4ca-648c-4d1b-a6c6-d2fb14eda983/1mb.mp4
opencast-presentation_1  | org.opencastproject.security.api.TrustedHttpClientException: java.net.ConnectException: Connection refused (Connection refused)
opencast-presentation_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:394) ~[?:?]
opencast-presentation_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:346) ~[?:?]
opencast-presentation_1  | 	at org.opencastproject.security.util.StandAloneTrustedHttpClientImpl$1.apply(StandAloneTrustedHttpClientImpl.java:128) ~[45:opencast-common:7.4.0]
opencast-presentation_1  | 	at org.opencastproject.security.util.StandAloneTrustedHttpClientImpl$1.apply(StandAloneTrustedHttpClientImpl.java:123) ~[45:opencast-common:7.4.0]
opencast-presentation_1  | 	at org.opencastproject.util.HttpUtil.waitForResource(HttpUtil.java:208) ~[45:opencast-common:7.4.0]
opencast-presentation_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.distributeElement(DownloadDistributionServiceImpl.java:346) [52:opencast-distribution-service-download:7.4.0]
```

**Comment by mtneug** [comment]
@edalex-tom thanks for the report and sorry for the long delay.

I could reproduce the error. When distributing files, the operation checks if the URL is available. In the example, this was not the case.

Note that in a production system you should think about how you set up the various URLs. For the download URL specifically, I would recommend using a normal webserver (or the presentation) to serve the files. However, in the example the admin instance is used once #126 gets merged.
