### ISSUE TITLE
Host is unreachable (Host unreachable)

### ISSUE THREAD

**Issue by bhargav0505** [opencast/opencast-docker#136]
15:54:40.326 [main] INFO  o.b.s.l.m.BesureListenerProcessManagerNonSeq - Initializing Listener
15:54:41.801 [main] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://192.168.1.112:8080: Host is unreachable (Host unreachable)
15:54:41.801 [main] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://192.168.1.112:8080
15:54:42.824 [main] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://192.168.1.112:8080: Host is unreachable (Host unreachable)
15:54:42.824 [main] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://192.168.1.112:8080
15:54:43.848 [main] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://192.168.1.112:8080: Host is unreachable (Host unreachable)
15:54:43.848 [main] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://192.168.1.112:8080
15:54:44.874 [main] ERROR o.b.s.l.m.BesureListenerProcessManagerNonSeq - ListenerProcessManager Initialization Exception:
org.besure.core.exception.BusinessException: Exception while executing deSerializeRestResponse methodjava.net.NoRouteToHostException: Host is unreachable (Host unreachable)
        at org.besure.client.ws.impl.BesureRestClient.triggerTheRequest(BesureRestClient.java:99)
        at org.besure.client.ws.impl.BesureRestClient.triggerTheRequest(BesureRestClient.java:23)
        at org.besure.client.common.impl.AbstractClient.connect(AbstractClient.java:26)
        at org.besure.services.cfg.client.BESURECfgClient.executeRequest(BESURECfgClient.java:235)
        at org.besure.services.cfg.client.BESURECfgClient.getConfigResponse(BESURECfgClient.java:222)
        at org.besure.services.cfg.client.BESURECfgClient.getConfig(BESURECfgClient.java:178)
        at org.besure.services.cfg.client.BESURECfgClient.getReceiverConfig(BESURECfgClient.java:304)
        at org.besure.service.core.app.manager.SimpleListenerProcessManager.initializeListener(SimpleListenerProcessManager.java:54)
        at org.besure.service.core.app.manager.SimpleListenerProcessManager.initialize(SimpleListenerProcessManager.java:39)
        at org.besure.services.listener.app.BesureListenerLauncher.main(BesureListenerLauncher.java:97)

**Comment by bhargav0505** [comment]
this is my dockerfile
FROM openjdk:8-jre-alpine
COPY /besure-life-cycle/besure-listener-service/target/lib lib
COPY /besure-life-cycle/besure-listener-service/target/besure-listener-service-1.1.0-SNAPSHOT.jar .
ENV CONFIG_SERVICE_IP 192.168.1.112
ENV CONFIG_PORT 8080
ENV PROCESS_MGR_THREAD_COUNT 10
ENV ENV_TARGET dev
EXPOSE 8080
STOPSIGNAL SIGTERM
CMD java -cp besure-listener-service-1.1.0-SNAPSHOT.jar:lib/* -Xms2048m -Xmx2048m -XX:CMSInitiatingOccupancyFraction=75 -DconfigServiceIP=$CONFIG_SERVICE_IP -DconfigServicePort=$CONFIG_PORT -DprocessManagerThreadCount=$PROCESS_MGR_THREAD_COUNT -DenvTarget=$ENV_TARGET org.besure.services.listener.app.BesureListenerLauncher

**Comment by mtneug** [comment]
This does not seem to be related to Opencast.
