### ISSUE TITLE
Connection refused (Connection refused)

### ISSUE THREAD

**Issue by bhargav0505** [opencast/opencast-docker#137]
below exception occuring while i am run the docker container

org.besure.core.exception.BusinessException: Exception while executing deSerializeRestResponse methodorg.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
        at org.besure.client.ws.impl.BesureRestClient.triggerTheRequest(BesureRestClient.java:99)
        at org.besure.client.ws.impl.BesureRestClient.triggerTheRequest(BesureRestClient.java:23)
        at org.besure.client.common.impl.AbstractClient.connect(AbstractClient.java:26)
        at org.besure.services.cfg.client.BESURECfgClient.executeRequest(BESURECfgClient.java:235)
        at org.besure.services.cfg.client.BESURECfgClient.getConfigResponse(BESURECfgClient.java:222)
        at org.besure.services.cfg.client.BESURECfgClient.getConfig(BESURECfgClient.java:178)
        at org.besure.services.cfg.client.BESURECfgClient.getReceiverConfig(BESURECfgClient.java:304)
        at org.besure.service.core.app.manager.SimpleListenerProcessManager.initializeListener(SimpleListenerProcessManager.java:54)
        at org.besure.service.core.app.manager.SimpleListenerProcessManager.initialize(SimpleListenerProcessManager.java:39)
        at org.besure.services.listener.app.BesureListenerLauncher.main(BesureListenerLauncher.java:97)

**Comment by mtneug** [comment]
@bhargav0505 you are either confusing this project with another one or this is spam! If you do not further clarify what you want to do and the steps I would need to take to get to this exception, I cannot help you. Again, this does not seem to be related to Opencast.
