### ISSUE TITLE
DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true when adding a new video

### ISSUE THREAD

**Issue by tm-ops** [opencast/opencast-docker#236]
We are using the https://github.com/opencast/opencast-docker/blob/master/docker-compose/docker-compose.allinone.postgres.yml definition with docker compose on a single Ubuntu Host.

opencast:
```
  opencast:
    image: quay.io/opencast/allinone:16.6

```
(pulled the latest image today...)

When creating a new event and uploading a video this fails and the docker container log shows this:

```

2024-11-06T15:42:45,699 | INFO  | (InboxScannerService:220) - Waiting for security context...
2024-11-06T15:42:47,413 | INFO  | (IngestServiceImpl:663) - Created mediapackage 0881c72b-1a7e-420b-8334-ebd46aee66be
2024-11-06T15:42:47,499 | INFO  | (IngestServiceImpl:762) - Start adding track 7318a481-e3f5-4b99-b1ff-409bdcd2d72a from input stream on mediapackage 0881c72b-1a7e-420b-8334-ebd46aee66be
2024-11-06T15:42:47,535 | INFO  | (IngestServiceImpl:1789) - Adding element of type Track to mediapackage 0881c72b-1a7e-420b-8334-ebd46aee66be
2024-11-06T15:42:47,550 | INFO  | (IngestServiceImpl:780) - Successful added track 7318a481-e3f5-4b99-b1ff-409bdcd2d72a on mediapackage 0881c72b-1a7e-420b-8334-ebd46aee66be at URL https://<redacted-base-url>/files/mediapackage/0881c72b-1a7e-420b-8334-ebd46aee66be/7318a481-e3f5-4b99-b1ff-409bdcd2d72a/file_example_MP4_480_1_5MG.mp4
2024-11-06T15:42:47,573 | INFO  | (IndexServiceImpl:1225) - Update asset track presenter/source
2024-11-06T15:42:47,900 | INFO  | (IngestServiceImpl:1258) - Starting a new workflow with ingested mediapackage 0881c72b-1a7e-420b-8334-ebd46aee66be based on workflow definition 'schedule-and-upload'
2024-11-06T15:42:47,900 | INFO  | (IngestServiceImpl:1649) - Ingested mediapackage 0881c72b-1a7e-420b-8334-ebd46aee66be is processed using workflow template 'schedule-and-upload', specified during ingest
2024-11-06T15:42:47,932 | INFO  | (IngestServiceImpl:1439) - No capture event found for id 0881c72b-1a7e-420b-8334-ebd46aee66be
2024-11-06T15:42:48,035 | INFO  | (IngestServiceImpl:1281) - Starting new workflow with ingested mediapackage '0881c72b-1a7e-420b-8334-ebd46aee66be' using the specified template 'schedule-and-upload'
2024-11-06T15:42:48,060 | INFO  | (AssetManagerImpl:1321) - Creating new version 0 of media package 0881c72b-1a7e-420b-8334-ebd46aee66be
[Fatal Error] :1:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
2024-11-06T15:42:48,450 | WARN  | (XACMLAuthorizationService:303) - Unable to load or parse Acl from URI https://oc.svak.at/assets/assets/assets/0881c72b-1a7e-420b-8334-ebd46aee66be/security-policy-episode/0/xacml.xml
org.opencastproject.authorization.xacml.XACMLParsingException: XACML could not be parsed
	at org.opencastproject.authorization.xacml.XACMLUtils.parseXacml(XACMLUtils.java:165) ~[?:?]
	at org.opencastproject.authorization.xacml.XACMLAuthorizationService.loadAcl(XACMLAuthorizationService.java:298) ~[?:?]
	at org.opencastproject.authorization.xacml.XACMLAuthorizationService.getAclByFlavor(XACMLAuthorizationService.java:197) ~[?:?]
	at org.opencastproject.authorization.xacml.XACMLAuthorizationService.getAcl(XACMLAuthorizationService.java:153) ~[?:?]
	at org.opencastproject.authorization.xacml.XACMLAuthorizationService.getActiveAcl(XACMLAuthorizationService.java:142) ~[?:?]
	at org.opencastproject.assetmanager.impl.AssetManagerImpl.lambda$updateEventInIndex$1(AssetManagerImpl.java:523) ~[?:?]
	at org.opencastproject.elasticsearch.index.ElasticsearchIndex.addOrUpdateEvent(ElasticsearchIndex.java:384) ~[?:?]
	at org.opencastproject.assetmanager.impl.AssetManagerImpl.updateEventInIndex(AssetManagerImpl.java:572) ~[?:?]
	at org.opencastproject.assetmanager.impl.AssetManagerImpl.takeSnapshot(AssetManagerImpl.java:445) ~[?:?]
	at org.opencastproject.assetmanager.util.WorkflowPropertiesUtil.storeProperties(WorkflowPropertiesUtil.java:125) ~[?:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.start(WorkflowServiceImpl.java:502) ~[?:?]
	at org.opencastproject.workflow.impl.WorkflowServiceImpl.start(WorkflowServiceImpl.java:477) ~[?:?]
	at org.opencastproject.ingest.impl.IngestServiceImpl.ingest(IngestServiceImpl.java:1287) ~[?:?]
	at org.opencastproject.ingest.impl.IngestServiceImpl.ingest(IngestServiceImpl.java:1217) ~[?:?]
	at org.opencastproject.index.service.impl.IndexServiceImpl.createEvent(IndexServiceImpl.java:996) ~[?:?]
	at org.opencastproject.index.service.impl.IndexServiceImpl.createEvent(IndexServiceImpl.java:836) ~[?:?]
	at org.opencastproject.index.service.impl.IndexServiceImpl.createEvent(IndexServiceImpl.java:626) ~[?:?]
	at org.opencastproject.adminui.endpoint.AbstractEventEndpoint.createNewEvent(AbstractEventEndpoint.java:2504) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[?:?]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[?:?]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[?:?]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[?:?]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[?:?]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[?:?]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[?:?]
	at org.opencastproject.kernel.rest.RestPublisher$RestServlet.handleRequest(RestPublisher.java:582) ~[?:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[?:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[!/:4.0.4]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet.service(OsgiInitializedServlet.java:102) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[!/:9.4.54.v20240208]
	at org.opencastproject.kernel.rest.JsonpFilter.doFilter(JsonpFilter.java:130) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.opencastproject.kernel.filter.proxy.TransparentProxyFilter.doFilter(TransparentProxyFilter.java:80) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.opencastproject.security.urlsigning.filter.UrlSigningFilter.doFilter(UrlSigningFilter.java:101) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.opencastproject.kernel.security.RemoteUserAndOrganizationFilter.doFilter(RemoteUserAndOrganizationFilter.java:265) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.opencastproject.kernel.rest.CurrentJobFilter.doFilter(CurrentJobFilter.java:107) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[?:?]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118) ~[?:?]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.opencastproject.kernel.security.AsyncTimeoutRedirectFilter.doFilter(AsyncTimeoutRedirectFilter.java:60) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:98) ~[?:?]
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) ~[?:?]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:102) ~[?:?]
	at org.springframework.security.web.authentication.www.DigestAuthenticationFilter.doFilter(DigestAuthenticationFilter.java:115) ~[?:?]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:102) ~[?:?]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:82) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:91) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:183) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:98) ~[?:?]
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:82) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) ~[?:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) ~[?:?]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192) ~[?:?]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) ~[?:?]
	at org.opencastproject.kernel.security.SecurityFilter.doFilter(SecurityFilter.java:141) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.opencastproject.kernel.security.OrganizationFilter.doFilter(OrganizationFilter.java:154) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.opencastproject.kernel.filter.https.HttpsFilter.doFilter(HttpsFilter.java:90) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.opencastproject.kernel.rest.CleanSessionsFilter.doFilter(CleanSessionsFilter.java:104) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedFilter.doFilter(OsgiInitializedFilter.java:176) ~[!/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebFilterHolder.doFilter(PaxWebFilterHolder.java:208) ~[!/:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.spi.servlet.OsgiFilterChain.doFilter(OsgiFilterChain.java:113) ~[!/:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletHandler.doHandle(PaxWebServletHandler.java:334) ~[!/:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) ~[!/:9.4.54.v20240208]
	at org.ops4j.pax.web.service.jetty.internal.PrioritizedHandlerCollection.handle(PrioritizedHandlerCollection.java:96) ~[!/:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [!/:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [!/:9.4.54.v20240208]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: org.xml.sax.SAXParseException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[?:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[?:?]
	at org.opencastproject.util.XmlSafeParser.parse(XmlSafeParser.java:187) ~[?:?]
	at org.opencastproject.util.XmlSafeParser.parse(XmlSafeParser.java:150) ~[?:?]
	at org.opencastproject.authorization.xacml.XACMLUtils.parseXacml(XACMLUtils.java:121) ~[?:?]
	... 160 more
2024-11-06T15:42:48,510 | WARN  | (DublinCoreXmlFormat:299) - Fatal error parsing DublinCore catalog: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
2024-11-06T15:42:50,700 | INFO  | (InboxScannerService:220) - Waiting for security context...
```

I tried adding JAVA_OPTS as env var:

`-Dorg.apache.xerces.xni.parser.XMLParserConfiguration=http://apache.org/xml/features/disallow-doctype-decl=false`

but then the container fails to start.

Is this issue only happening for us? Do you have any advice on how to debug this further or maybe fix this issue?
Or is there a workaround?
Thanks.

**Comment by mtneug** [comment]
How do you upload the video? More specifically, how are the ACLs created/uploaded? The error message indicates that there is an error parsing the ACL XML file.

Also, this URL is strange and probably the reason for the parsing error:
```
https://oc.svak.at/assets/assets/assets/0881c72b-1a7e-420b-8334-ebd46aee66be/security-policy-episode/0/xacml.xml
```

The asset manager has the path prefix `assets/assets` and not `assets/assets/assets`. Did you change the asset manger URL?

**Comment by tm-ops** [comment]
> How do you upload the video? More specifically, how are the ACLs created/uploaded? The error message indicates that there is an error parsing the ACL XML file.
> 
> Also, this URL is strange and probably the reason for the parsing error:
> 
> ```
> https://oc.svak.at/assets/assets/assets/0881c72b-1a7e-420b-8334-ebd46aee66be/security-policy-episode/0/xacml.xml
> ```
> 
> The asset manager has the path prefix `assets/assets` and not `assets/assets/assets`. Did you change the asset manger URL?

Hi Matthias, thx for your reply. We used the normal upload via web ui => Add event => Source choose video

https://<base-url>/admin-ui/index.html#:~:text=Add-,event,-Actions

And yes, we have two organizations and therefor created a second 

org.opencastproject.organization-<orgname>.cfg   file

and changed quite a few urls - also the mentioned asset url - thx for pointing this out.

old:
```
prop.org.opencastproject.external.api.url=https://<base-url>/api
prop.org.opencastproject.assetmanager.url=https://<base-url>/assets
```

We now changed these url to reflect only the <base-url>:
new:
```
prop.org.opencastproject.external.api.url=https://<base-url>
prop.org.opencastproject.assetmanager.url=https://<base-url>
```

And the error is gone and the vid is uploaded as expected! Thank you very much for your help @mtneug !
