### ISSUE TITLE
NoRouteToHostException: Host is unreachable in Docker

### ISSUE THREAD

**Issue by baalchina** [opencast/opencast-docker#77]
Hey guys,

I am using docker-compose 1.19, in a CentOS 7 system.

After start docker like this,

`$ export HOSTIP=10.100.176.131 `  
`$ docker-compose -f docker-compose/docker-compose.allinone.h2.yml up`
The website of opencast is fine, after upload a mp4 file, I got a error here:

```
opencast_1  | 2018-02-14 16:55:34,245 | INFO  | (FFmpegSilenceDetector:148) - Track /data/opencast/workspace/mediapackage/246b655f-d6d3-4f6f-804c-9fa793b938f7/a4a842d0-15c4-44bb-b498-05f5ad346b30/__________.mp4 loaded, duration is 60 s
opencast_1  | 2018-02-14 16:55:34,246 | INFO  | (FFmpegSilenceDetector:150) - Starting silence detection of /data/opencast/workspace/mediapackage/246b655f-d6d3-4f6f-804c-9fa793b938f7/a4a842d0-15c4-44bb-b498-05f5ad346b30/__________.mp4
opencast_1  | 2018-02-14 16:55:34,246 | INFO  | (FFmpegSilenceDetector:158) - Running ffmpeg -nostats -i /data/opencast/workspace/mediapackage/246b655f-d6d3-4f6f-804c-9fa793b938f7/a4a842d0-15c4-44bb-b498-05f5ad346b30/__________.mp4 -filter:a silencedetect=noise=-40dB:duration=10.000 -f null -
opencast_1  | 2018-02-14 16:55:34,540 | INFO  | (FFmpegSilenceDetector:190) - No silence found. Adding one large segment.
opencast_1  | 2018-02-14 16:55:34,542 | INFO  | (FFmpegSilenceDetector:238) - Segmentation of track a4a842d0-15c4-44bb-b498-05f5ad346b30 yielded 1 segments
opencast_1  | 2018-02-14 16:55:39,291 | INFO  | (SilenceDetectionWorkflowOperationHandler:216) - Finished silence detection on track a4a842d0-15c4-44bb-b498-05f5ad346b30
opencast_1  | 2018-02-14 16:55:44,313 | INFO  | (TagWorkflowOperationHandler:122) - Retagging mediapackage elements
opencast_1  | 2018-02-14 16:55:49,368 | INFO  | (ConfigurablePublishWorkflowOperationHandler:289) - Start bulk publishing of 2 elements of media package '246b655f-d6d3-4f6f-804c-9fa793b938f7' to publication channel 'internal'
opencast_1  | 2018-02-14 16:55:58,333 | WARN  | (DownloadDistributionServiceImpl:359) - Error distributing http://opencast:8080/files/mediapackage/246b655f-d6d3-4f6f-804c-9fa793b938f7/44734aaf-e614-4c52-874a-d096ad411655/waveform.png
opencast_1  | org.opencastproject.security.api.TrustedHttpClientException: java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
opencast_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:392)[106:matterhorn-kernel:4.1.0]
opencast_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:345)[106:matterhorn-kernel:4.1.0]
opencast_1  | 	at org.opencastproject.security.util.StandAloneTrustedHttpClientImpl$1.apply(StandAloneTrustedHttpClientImpl.java:128)[55:matterhorn-common:4.1.0]
opencast_1  | 	at org.opencastproject.security.util.StandAloneTrustedHttpClientImpl$1.apply(StandAloneTrustedHttpClientImpl.java:123)[55:matterhorn-common:4.1.0]
opencast_1  | 	at org.opencastproject.util.HttpUtil.waitForResource(HttpUtil.java:208)[55:matterhorn-common:4.1.0]
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.distributeElement(DownloadDistributionServiceImpl.java:346)[73:matterhorn-distribution-service-download:4.1.0]
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.distributeElements(DownloadDistributionServiceImpl.java:244)[73:matterhorn-distribution-service-download:4.1.0]
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.process(DownloadDistributionServiceImpl.java:501)[73:matterhorn-distribution-service-download:4.1.0]
opencast_1  | 	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:282)[55:matterhorn-common:4.1.0]
opencast_1  | 	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:241)[55:matterhorn-common:4.1.0]
opencast_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_151]
opencast_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_151]
opencast_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_151]
opencast_1  | 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_151]
opencast_1  | Caused by: java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
opencast_1  | 	at java.net.PlainSocketImpl.socketConnect(Native Method)[:1.8.0_151]
opencast_1  | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)[:1.8.0_151]
opencast_1  | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)[:1.8.0_151]
opencast_1  | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)[:1.8.0_151]
opencast_1  | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)[:1.8.0_151]
opencast_1  | 	at java.net.Socket.connect(Socket.java:589)[:1.8.0_151]
opencast_1  | 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)[236:org.apache.httpcomponents.httpclient:4.5.0]
opencast_1  | 	at org.opencastproject.kernel.http.impl.HttpClientImpl.execute(HttpClientImpl.java:77)[106:matterhorn-kernel:4.1.0]
opencast_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:385)[106:matterhorn-kernel:4.1.0]
opencast_1  | 	... 13 more
opencast_1  | 2018-02-14 16:55:58,340 | INFO  | (ServiceRegistryJpaImpl:2436) - State set to WARNING for current service org.opencastproject.distribution.download on host http://opencast:8080
opencast_1  | 2018-02-14 16:55:58,355 | ERROR | (AbstractJobProducer$JobRunner:312) - Error handling operation 'Distribute': org.opencastproject.serviceregistry.api.ServiceRegistryException: Error handling operation 'Distribute'
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.process(DownloadDistributionServiceImpl.java:517)
opencast_1  | 	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:282)
opencast_1  | 	at org.opencastproject.job.api.AbstractJobProducer$JobRunner.call(AbstractJobProducer.java:241)
opencast_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
opencast_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
opencast_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
opencast_1  | 	at java.lang.Thread.run(Thread.java:748)
opencast_1  | Caused by: org.opencastproject.distribution.api.DistributionException: org.opencastproject.security.api.TrustedHttpClientException: java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.distributeElement(DownloadDistributionServiceImpl.java:363)
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.distributeElements(DownloadDistributionServiceImpl.java:244)
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.process(DownloadDistributionServiceImpl.java:501)
opencast_1  | 	... 6 more
opencast_1  | Caused by: org.opencastproject.security.api.TrustedHttpClientException: java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
opencast_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:392)
opencast_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:345)
opencast_1  | 	at org.opencastproject.security.util.StandAloneTrustedHttpClientImpl$1.apply(StandAloneTrustedHttpClientImpl.java:128)
opencast_1  | 	at org.opencastproject.security.util.StandAloneTrustedHttpClientImpl$1.apply(StandAloneTrustedHttpClientImpl.java:123)
opencast_1  | 	at org.opencastproject.util.HttpUtil.waitForResource(HttpUtil.java:208)
opencast_1  | 	at org.opencastproject.distribution.download.DownloadDistributionServiceImpl.distributeElement(DownloadDistributionServiceImpl.java:346)
opencast_1  | 	... 8 more
opencast_1  | Caused by: java.net.NoRouteToHostException: Host is unreachable (Host unreachable)
opencast_1  | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
opencast_1  | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
opencast_1  | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
opencast_1  | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
opencast_1  | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
opencast_1  | 	at java.net.Socket.connect(Socket.java:589)
opencast_1  | 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
opencast_1  | 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
opencast_1  | 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
opencast_1  | 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
opencast_1  | 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
opencast_1  | 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
opencast_1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
opencast_1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
opencast_1  | 	at org.opencastproject.kernel.http.impl.HttpClientImpl.execute(HttpClientImpl.java:77)
opencast_1  | 	at org.opencastproject.kernel.security.TrustedHttpClientImpl.execute(TrustedHttpClientImpl.java:385)
opencast_1  | 	... 13 more
opencast_1  | 
opencast_1  | 2018-02-14 16:55:59,376 | ERROR | (WorkflowOperationWorker:182) - Workflow operation 'operation:'publish-configure', position:21, state:'FAILED'' failed
opencast_1  | org.opencastproject.workflow.api.WorkflowOperationException: At least one of the distribution jobs did not complete successfully
opencast_1  | 	at org.opencastproject.workflow.handler.distribution.ConfigurablePublishWorkflowOperationHandler.distribute(ConfigurablePublishWorkflowOperationHandler.java:317)[74:matterhorn-distribution-workflowoperation:4.1.0]
opencast_1  | 	at org.opencastproject.workflow.handler.distribution.ConfigurablePublishWorkflowOperationHandler.start(ConfigurablePublishWorkflowOperationHandler.java:236)[74:matterhorn-distribution-workflowoperation:4.1.0]
opencast_1  | 	at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:233)[185:matterhorn-workflow-service-impl:4.1.0]
opencast_1  | 	at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:155)[185:matterhorn-workflow-service-impl:4.1.0]
opencast_1  | 	at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:885)[185:matterhorn-workflow-service-impl:4.1.0]
opencast_1  | 	at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1895)[185:matterhorn-workflow-service-impl:4.1.0]
opencast_1  | 	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2315)[185:matterhorn-workflow-service-impl:4.1.0]
opencast_1  | 	at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2281)[185:matterhorn-workflow-service-impl:4.1.0]
opencast_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_151]
opencast_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_151]
opencast_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_151]
opencast_1  | 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_151]
opencast_1  | 2018-02-14 16:56:09,454 | INFO  | (AssetManagerSnapshotWorkflowOperationHandler:104) - Take snapshot of media package 246b655f-d6d3-4f6f-804c-9fa793b938f7
opencast_1  | 2018-02-14 16:56:09,460 | INFO  | (AbstractAssetManager:172) - Creating new version 1 of media package 246b655f-d6d3-4f6f-804c-9fa793b938f7
opencast_1  | 2018-02-14 16:56:09,472 | INFO  | (AssetManagerWithMessaging:207) - Send update message for snapshot 246b655f-d6d3-4f6f-804c-9fa793b938f7, 1 to ActiveMQ
opencast_1  | 2018-02-14 16:56:09,483 | INFO  | (WorkspaceImpl:392) - Downloading http://opencast:8080/assets/assets/246b655f-d6d3-4f6f-804c-9fa793b938f7/7eae3512-f4b6-49ff-b41f-157e348f57b1/1/dublincore.xml to /data/opencast/workspace/http_opencast_8080/assets/assets/246b655f-d6d3-4f6f-804c-9fa793b938f7/7eae3512-f4b6-49ff-b41f-157e348f57b1/1/dublincore.xml
opencast_1  | 2018-02-14 16:56:15,513 | INFO  | (WorkingFileRepositoryImpl:172) - [>a5336c92] Unable to delete non existing media package element 6df209b8-ca65-405d-8643-d19e6cb383e4@246b655f-d6d3-4f6f-804c-9fa793b938f7
^CGracefully stopping... (press Ctrl+C again to force)
```

Then the job failed,  I got a error in Service tab.
which service name is org.opencastproject.distribution.download, and status warning.

So, is there any thing wrong with my setps? Thanks.

BTW, selinux and firewall all stopped in CentOS.

**Comment by mtneug** [comment]
What version of Docker are you using? Could you post the output the `docker version`?

**Comment by baalchina** [comment]
Hi mtneug, here is docker version

`[root@localhost opencast-docker]# docker -v
Docker version 17.05.0-ce, build 89658be`

Thanks.

**Comment by mtneug** [comment]
Good, that version should definitely work. Could you run these commands to check if the Docker DNS system works in principle? These will create a new Docker network and a container that resolves its hostname, looks at the network interfaces and pings itself:

```sh
docker network create test
docker run --name opencast --rm -it --net test alpine:3.7 sh -c 'nslookup opencast && ifconfig && ping -c 4 opencast'
```

**Comment by baalchina** [comment]
Thanks mtneug, I solved this problem.
I run export and docker-compose command in root, seems the system variable doesn't work in docker?
After add variable in /etc/profile, everything works fine.

**Comment by mtneug** [comment]
Then I guess it was a temporal problem. The `HOSTIP` variable should actually not produce this error message. It only determines which host the browser should use to download media.
